<script lang="ts">
  import type { Component } from 'svelte';
  import {
    AlertCircle,
    BadgeCheck,
    Bell,
    BellOff,
    BellRing,
    BookCheck,
    BookOpen,
    Bookmark,
    Calendar,
    Camera,
    Check,
    CheckCircle2,
    ChevronRight,
    CircleHelp,
    ClipboardCheck,
    Clock,
    Code2,
    Compass,
    FileText,
    FlaskConical,
    Heart,
    Home,
    Inbox,
    Info,
    KeyRound,
    Layers3,
    LayoutDashboard,
    LockKeyhole,
    LogIn,
    LogOut,
    Mail,
    Menu,
    MessageCircle,
    MessageSquare,
    Moon,
    Network,
    PanelLeft,
    Search,
    Send,
    Settings,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    Sparkles,
    Sun,
    Target,
    Trophy,
    UserCheck,
    UserPlus,
    UserRound,
    Users,
    Wallet,
    X,
    Zap
  } from '@lucide/svelte';

  type IconProps = {
    size?: number | string;
    strokeWidth?: number | string;
    class?: string;
    'aria-hidden'?: boolean | 'true' | 'false';
  };

  type IconComponent = Component<IconProps>;

  type Props = {
    name: string;
    size?: number;
    strokeWidth?: number;
    class?: string;
  };

  let { name, size = 18, strokeWidth = 1.9, class: className = '' }: Props = $props();

  const icons: Record<string, IconComponent> = {
    alert: AlertCircle,
    warning: AlertCircle,
    badge: BadgeCheck,
    passport: BadgeCheck,
    verified: BadgeCheck,
    bell: Bell,
    notification: Bell,
    notifications: Bell,
    'bell-ring': BellRing,
    unread: BellRing,
    'bell-off': BellOff,
    read: BellOff,
    book: BookOpen,
    'book-open': BookOpen,
    core: BookOpen,
    learn: BookOpen,
    lesson: BookOpen,
    'book-check': BookCheck,
    bookmark: Bookmark,
    saved: Bookmark,
    calendar: Calendar,
    event: Calendar,
    camera: Camera,
    check: CheckCircle2,
    done: CheckCircle2,
    success: CheckCircle2,
    completed: CheckCircle2,
    tick: Check,
    'chevron-right': ChevronRight,
    help: CircleHelp,
    faq: CircleHelp,
    clipboard: ClipboardCheck,
    checklist: ClipboardCheck,
    clock: Clock,
    time: Clock,
    code: Code2,
    docs: FileText,
    document: FileText,
    file: FileText,
    compass: Compass,
    hub: Compass,
    explore: Compass,
    'flask-conical': FlaskConical,
    flask: FlaskConical,
    lab: FlaskConical,
    practice: FlaskConical,
    heart: Heart,
    like: Heart,
    home: Home,
    inbox: Inbox,
    info: Info,
    key: KeyRound,
    layers: Layers3,
    stack: Layers3,
    dashboard: LayoutDashboard,
    grid: LayoutDashboard,
    lock: LockKeyhole,
    login: LogIn,
    enter: LogIn,
    logout: LogOut,
    exit: LogOut,
    mail: Mail,
    menu: Menu,
    message: MessageCircle,
    messages: MessageCircle,
    chat: MessageCircle,
    comment: MessageSquare,
    comments: MessageSquare,
    moon: Moon,
    network: Network,
    community: Users,
    panel: PanelLeft,
    search: Search,
    send: Send,
    settings: Settings,
    share: Share2,
    'share-2': Share2,
    shield: ShieldCheck,
    safety: ShieldCheck,
    secure: ShieldCheck,
    security: ShieldCheck,
    'shield-check': ShieldCheck,
    'shield-alert': ShieldAlert,
    risk: ShieldAlert,
    sparkles: Sparkles,
    spark: Sparkles,
    sun: Sun,
    target: Target,
    trophy: Trophy,
    achievement: Trophy,
    user: UserRound,
    'user-round': UserRound,
    profile: UserRound,
    account: UserRound,
    'user-plus': UserPlus,
    follow: UserPlus,
    friend: UserPlus,
    'user-check': UserCheck,
    users: Users,
    group: Users,
    wallet: Wallet,
    x: X,
    close: X,
    zap: Zap,
    energy: Zap,
    default: Sparkles
  };

  const normalizedName = $derived((name || 'default').trim());
  const Icon = $derived(icons[normalizedName] ?? icons[normalizedName.toLowerCase()] ?? Sparkles);
  const iconClass = $derived(['spark-icon', className].filter(Boolean).join(' '));
</script>

<Icon {size} {strokeWidth} class={iconClass} aria-hidden="true" />
